permalink: /:year/:month/:day/:title
url: https://blog.webdesign.bradykondek.ga
baseurl: /blog

# variables
name: Blog | Brady Kondek Website Design
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
